name: Generate README

on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm i --package-lock-only
      - run: npm install
      - run: npm ci

      - name: Generate quote
        run: npm run generate

      - name: Update README.md
        run: |
          git config --global user.email "nguyendinhkhanhnguyen1@gmail.com"
          git config --global user.name "KNguyen-1411"
          git add README.md 
          git commit -m "[UPDATE] Updated README.md" || echo "No changes to commit"
          git push origin master
